ARDUINO_CLI := ./bin/arduino-cli --config-file ./lib/arduino-cli.yaml
APP_NAME := tests
ARDUINO_LIBS := \
	AUnit

ARDUINO_LIB_DIR := ./lib/
ARDUINO_LIB_DIRS := \
	../lib \
	../lib/libraries

include ../lib/EpoxyDuino/EpoxyDuino.mk
